version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Yerevan
    groups:
      development-minor-patch:
        patterns: ['*']
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: Asia/Yerevan
    groups:
      actions-minor-patch:
        patterns: ['*']
        update-types: [minor, patch]
    open-pull-requests-limit: 5
